build_crispacuda:
  image: nvidia/cuda:11.6.1-cudnn8-devel-ubuntu20.04
  script:
    - make crispacuda
  artifacts:
    paths:
      - crispacuda

build_image:
  needs:
    - job: build_crispacuda
      artifacts: true
  image: docker:23.0.6
  tags:
    - autoscale-large
  services:
    - name: docker:23.0.6-dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:${CI_DEFAULT_BRANCH} || true
    - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH} || true
    - docker build
      --cache-from $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}
      --cache-from $CI_REGISTRY_IMAGE:${CI_DEFAULT_BRANCH}
      --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}
      --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}
      .
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}

