build_crispacuda:
  image: nvidia/cuda:11.6.1-cudnn8-devel-ubuntu20.04
  script:
    - make crispacuda
  artifacts:
    paths:
      - crispacuda

build_image:
  needs:
    - job: build_crispacuda
      artifacts: true
  image: docker:23.0.6
  tags:
    - autoscale-large
  services:
    - name: docker:23.0.6-dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build .
